# Generated by Django 2.2.2 on 2019-08-24 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imdbreviews', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('content', models.CharField(max_length=400)),
                ('movie_id', models.CharField(max_length=10)),
                ('rating', models.IntegerField()),
                ('helpfulness', models.IntegerField()),
                ('user_reviewed', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='movie',
            name='actors',
        ),
        migrations.AddField(
            model_name='movie',
            name='actors',
            field=models.ManyToManyField(related_name='_movie_actors_+', to='imdbreviews.Movie'),
        ),
    ]
