# Generated by Django 2.2.2 on 2019-08-27 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imdbreviews', '0002_auto_20190824_0517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='actors',
        ),
        migrations.AddField(
            model_name='movie',
            name='actors',
            field=models.CharField(default=['Lindsay Lohan', 'Anne Hathaway', 'Taylor Swift', 'Emma Watson', 'Selena Gomez', 'Meryl Streep'], max_length=100000),
        ),
    ]
