# Generated by Django 2.2.2 on 2019-08-28 02:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('imdbreviews', '0003_auto_20190827_0258'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='number_voted',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='review_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='review',
            name='review_id',
            field=models.CharField(default=12345, max_length=10),
            preserve_default=False,
        ),
    ]
