# Generated by Django 2.2.2 on 2019-09-17 04:58

from django.db import migrations
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('imdbreviews', '0005_auto_20190904_0434'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='users_reviewed',
            field=picklefield.fields.PickledObjectField(default={}, editable=False),
            preserve_default=False,
        ),
    ]
