# Generated by Django 2.2.2 on 2019-09-20 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imdbreviews', '0006_review_users_reviewed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='num_reviews',
        ),
    ]
